# Generated by Django 3.0.6 on 2020-05-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celery_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prices',
            name='winner',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
