# Generated by Django 3.0.6 on 2020-05-24 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('celery_app', '0002_prices_winner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgForAuction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='file')),
                ('auction', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='celery_app.Auctions')),
            ],
        ),
    ]
