# Generated by Django 3.0.6 on 2020-06-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celery_app', '0003_imgforauction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='sort_auction',
            field=models.TimeField(blank=True),
        ),
    ]
