# Generated by Django 3.0.6 on 2020-06-04 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celery_app', '0004_auto_20200604_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='sort_auction',
            field=models.IntegerField(blank=True),
        ),
    ]
