# Generated by Django 3.0.6 on 2020-06-04 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('celery_app', '0005_auto_20200604_0737'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleAuction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_time', models.DateTimeField()),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='celery_app.Auctions')),
            ],
        ),
    ]
