# Generated by Django 3.0.6 on 2020-06-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celery_app', '0006_scheduleauction'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='start_auction_time',
            field=models.CharField(default=11, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduleauction',
            name='active_date_time',
            field=models.CharField(default=11, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auctions',
            name='main_img',
            field=models.ImageField(upload_to='file'),
        ),
    ]
