# Generated by Django 3.0.6 on 2020-06-07 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celery_app', '0007_auto_20200606_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleauction',
            name='active_time',
            field=models.DateField(),
        ),
    ]
