# Generated by Django 3.0.6 on 2020-06-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celery_app', '0008_auto_20200607_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleauction',
            name='active_time',
            field=models.DateTimeField(),
        ),
    ]
