# Generated by Django 3.0.6 on 2020-06-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celery_app', '0009_auto_20200607_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleauction',
            name='active_time',
            field=models.DateField(),
        ),
    ]
