# Generated by Django 3.0.6 on 2020-06-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celery_app', '0010_auto_20200607_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleauction',
            name='active_date_time',
            field=models.IntegerField(max_length=6),
        ),
    ]
